[2022-07-28 19:58:55,471] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: btc_price_operator.get_btc manual__2022-07-28T19:58:53.780790+00:00 [queued]>
[2022-07-28 19:58:55,481] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: btc_price_operator.get_btc manual__2022-07-28T19:58:53.780790+00:00 [queued]>
[2022-07-28 19:58:55,481] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2022-07-28 19:58:55,481] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2022-07-28 19:58:55,481] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-07-28 19:58:55,493] {taskinstance.py:1262} INFO - Executing <Task(_PythonDecoratedOperator): get_btc> on 2022-07-28 19:58:53.780790+00:00
[2022-07-28 19:58:55,497] {standard_task_runner.py:52} INFO - Started process 92 to run task
[2022-07-28 19:58:55,500] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'btc_price_operator', 'get_btc', 'manual__2022-07-28T19:58:53.780790+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/btc_price.py', '--cfg-path', '/tmp/tmppym8eerf', '--error-file', '/tmp/tmpq1vo1arr']
[2022-07-28 19:58:55,501] {standard_task_runner.py:77} INFO - Job 91: Subtask get_btc
[2022-07-28 19:58:55,543] {logging_mixin.py:109} INFO - Running <TaskInstance: btc_price_operator.get_btc manual__2022-07-28T19:58:53.780790+00:00 [running]> on host aeed186f5814
[2022-07-28 19:58:55,594] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=btc_price_operator
AIRFLOW_CTX_TASK_ID=get_btc
AIRFLOW_CTX_EXECUTION_DATE=2022-07-28T19:58:53.780790+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-28T19:58:53.780790+00:00
[2022-07-28 19:58:55,595] {taskinstance.py:1703} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 134, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 151, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/btc_price.py", line 25, in get_btc
    return {'prices': BTCPrice.get_prices()}
AttributeError: type object 'BTCPrice' has no attribute 'get_prices'
[2022-07-28 19:58:55,607] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=btc_price_operator, task_id=get_btc, execution_date=20220728T195853, start_date=20220728T195855, end_date=20220728T195855
[2022-07-28 19:58:55,621] {standard_task_runner.py:91} ERROR - Failed to execute job 91 for task get_btc
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 134, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 151, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/btc_price.py", line 25, in get_btc
    return {'prices': BTCPrice.get_prices()}
AttributeError: type object 'BTCPrice' has no attribute 'get_prices'
[2022-07-28 19:58:55,633] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-07-28 19:58:55,653] {baseoperator.py:1386} WARNING - Dependency <Task(_PythonDecoratedOperator): compose_price_email>, send_price_email already registered for DAG: btc_price_operator
[2022-07-28 19:58:55,653] {baseoperator.py:1386} WARNING - Dependency <Task(EmailOperator): send_price_email>, compose_price_email already registered for DAG: btc_price_operator
[2022-07-28 19:58:55,653] {baseoperator.py:1386} WARNING - Dependency <Task(_PythonDecoratedOperator): compose_price_email>, send_price_email already registered for DAG: btc_price_operator
[2022-07-28 19:58:55,653] {baseoperator.py:1386} WARNING - Dependency <Task(EmailOperator): send_price_email>, compose_price_email already registered for DAG: btc_price_operator
[2022-07-28 19:58:55,653] {baseoperator.py:1386} WARNING - Dependency <Task(_PythonDecoratedOperator): compose_price_email>, send_price_email already registered for DAG: btc_price_operator
[2022-07-28 19:58:55,653] {baseoperator.py:1386} WARNING - Dependency <Task(EmailOperator): send_price_email>, compose_price_email already registered for DAG: btc_price_operator
[2022-07-28 19:58:55,654] {baseoperator.py:1386} WARNING - Dependency <Task(_PythonDecoratedOperator): compose_price_email>, send_price_email already registered for DAG: btc_price_operator
[2022-07-28 19:58:55,654] {baseoperator.py:1386} WARNING - Dependency <Task(EmailOperator): send_price_email>, compose_price_email already registered for DAG: btc_price_operator
[2022-07-28 19:58:55,654] {baseoperator.py:1386} WARNING - Dependency <Task(_PythonDecoratedOperator): compose_price_email>, send_price_email already registered for DAG: btc_price_operator
[2022-07-28 19:58:55,654] {baseoperator.py:1386} WARNING - Dependency <Task(EmailOperator): send_price_email>, compose_price_email already registered for DAG: btc_price_operator
[2022-07-28 19:58:55,670] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
